services:
  mysql:
    build:
      context: ./mysql
      dockerfile: Dockerfile
    container_name: mysql
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: my-secret-password
      MYSQL_DATABASE: nest_angular_dev
      MYSQL_USER: nest_user
      MYSQL_PASSWORD: nest_password
    volumes:
      - db_data:/var/lib/mysql # Pour persister les données
      - ./mysql/nest_angular_dev.sql:/docker-entrypoint-initdb.d/init.sql:ro # Script d'initialisation
    networks:
      - app-network
  backend:
    build:
      context: . # Répertoire contenant le Dockerfile de NestJS
      dockerfile: Dockerfile
    container_name: nest-backend
    ports:
      - "3000:3000" # Expose le backend sur le port 3000
    environment:
      - NODE_ENV=production
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_USER=root
      - DB_PASSWORD=my-secret-password
      - DB_NAME=nest_angular_dev
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  db_data: